DROP DATABASE IF EXISTS parqueadero;
CREATE DATABASE parqueadero;
USE parqueadero;

CREATE TABLE ESTADOS (
	ID_ESTADO BIT PRIMARY KEY,
    ESTADO_NOMB VARCHAR(10) NOT NULL
);

CREATE TABLE ESTACIONAMIENTOS (
	ID_ESTACIONAMIENTO INT PRIMARY KEY,
    ID_ESTADO BIT,
    CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE TICKETS (
	ID_TICKET INT PRIMARY KEY AUTO_INCREMENT,
    HORA_ING TIMESTAMP 
);

CREATE TABLE VEHICULOS (
    ID_VEHICULO INT PRIMARY KEY AUTO_INCREMENT,
    PLACA VARCHAR(10) NOT NULL,
    PROPIETARIO VARCHAR(50) NOT NULL,
    ID_TICKET INT,
    ID_ESTACIONAMIENTO INT,
    CONSTRAINT FKV_ID_ESTACIONAMIENTO FOREIGN KEY (ID_ESTACIONAMIENTO) REFERENCES ESTACIONAMIENTOS(ID_ESTACIONAMIENTO),
    CONSTRAINT FKV_ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKETS(ID_TICKET)
);

CREATE TABLE FACTURAS (
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_PAGADO FLOAT,
	ID_VEHICULO INT,
    ID_TICKET INT,
    CONSTRAINT FKF_ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKETS(ID_TICKET),
    CONSTRAINT FK_ID_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS(ID_VEHICULO)
);


