DROP DATABASE IF EXISTS parqueadero;
CREATE DATABASE parqueadero;
USE parqueadero;

CREATE TABLE VEHICULO (
    ID_VEHICULO INT PRIMARY KEY AUTO_INCREMENT,
    PLACA VARCHAR(10),
    PROPIETARIO VARCHAR(50)
);

CREATE TABLE TICKET (
	ID_TICKET INT PRIMARY KEY AUTO_INCREMENT,
    HORA_ING TIMESTAMP 
);

CREATE TABLE ESTADOS (
	ID_ESTADO BIT PRIMARY KEY,
    ESTADO_NOMB VARCHAR(10) NOT NULL
);

CREATE TABLE ESTACIONAMIENTO (
	ID_ESTACIONAMIENTO INTEGER PRIMARY KEY,
    ID_ESTADO BIT,
    CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE FACTURA (
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_PAGADO FLOAT,
	ID_VEHICULO INT,
    ID_TICKET INT,
    CONSTRAINT FK_ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKET(ID_TICKET),
    CONSTRAINT FK_ID_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO)
);


