INSERT INTO ESTADOS VALUES
(0, 'VACIO'),
(1, 'OCUPADO');

INSERT INTO VEHICULO (PLACA, PROPIETARIO) VALUES
('ABC123', 'Juan Pérez'),
('XYZ987', 'Ana Gómez'),
('LMN456', 'Carlos Ruiz');

INSERT INTO ESTACIONAMIENTO (ID_ESTACIONAMIENTO, ID_ESTADO) VALUES
(1, 0),
(2, 0),
(3, 0);

INSERT INTO FACTURA (VALOR_PAGADO, ID_VEHICULO, ID_TICKET) VALUES
(10.00, 1, 1),
(20.00, 2, 2),
(15.00, 3, 3);
