-- FUNCION no hay porque solo pidio un procedimeitno para est punto

-- TRIGGER (el select into no era necesario porque cuando el trigger se dispara
-- el mysql ya da los valores de antes y despues)
DELIMITER $$
CREATE TRIGGER T_VALIDAR_ESTADO
BEFORE UPDATE ON ESTACIONAMIENTO
FOR EACH ROW
BEGIN
	IF OLD.ID_ESTADO = 1 AND NEW.ESTADO = 1 THEN
    SIGNAL SQLSTATE '4500' SET MESSAGE_TEXT = 'EL ESTACIONAMIENTO ESTA OCUPADO';
    END IF;
END $$

DELIMITER ;



-- PROCEDIMIENTO ALM
USE `parqueadero`;
DROP procedure IF EXISTS `P_TICKET`;

DELIMITER $$
USE `parqueadero`$$
CREATE PROCEDURE `P_TICKET` (
IN P_ID_VEHICULO INT,
IN P_ID_ESTACIONAMIENTO INT
)
BEGIN
    UPDATE ESTACIONAMIENTO SET ID_ESTADO = 1 
    WHERE ID_ESTACIONAMIENTO = P_ID_ESTACIONAMIENTO;
    INSERT INTO TICKET (HORA_ING) VALUES (NOW());
END$$

DELIMITER ;