-- FUNCION
USE `parqueadero`;
DROP function IF EXISTS `F_CALCULAR_VALOR`;

DELIMITER $$
USE `parqueadero`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `F_CALCULAR_VALOR`(
HORA_ING TIMESTAMP) 
RETURNS FLOAT(10,2)
BEGIN
	DECLARE VALOR_TOTAL FLOAT;
    DECLARE MINUTOS FLOAT;
    SET MINUTOS = TIMESTAMPDIFF(MINUTE, HORA_ING, NOW());
    SET VALOR_TOTAL = MINUTOS * 2;
RETURN VALOR_TOTAL;
END$$

DELIMITER ;
;



-- PROCEDIMIENTO ALM
USE `parqueadero`;
DROP procedure IF EXISTS `P_FACTURA`;

DELIMITER $$
USE `parqueadero`$$
CREATE PROCEDURE `P_FACTURA` (
IN P_HORA_ING TIMESTAMP, 
IN P_VALOR_PAGADO INT, 
IN P_ID_VEHICULO INT,
IN P_PLACA VARCHAR(10),
IN VALOR_PAGADO FLOAT)
BEGIN
	SET VALOR_PAGADO = F_CALCULAR_VALOR(HORA_ING);
    
	INSERT INTO FACTURA (HORA_ING, VALOR_PAGADO, ID_VEHICULO, PLACA, VALOR_PAGADO)
    VALUES (P_HORA_ING, P_VALOR_PAGADO, P_ID_VEHICULO, P_PLACA, P_VALOR_PAGADO);
END$$

DELIMITER ;



-- TRIGGER
DELIMITER $$
CREATE TRIGGER T_VALIDAR_PAGO
BEFORE UPDATE ON FACTURA
FOR EACH ROW
BEGIN
    DECLARE VALOR_REAL INT;
    SET VALOR_REAL = F_CALCULAR_VALOR(HORA_ING);

    IF NEW.valor_pagado < valor_real THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Pago insuficiente.';
    END IF;
END $$

DELIMITER ;



