-- FUNCION
USE `hotel`;
DROP function IF EXISTS `F_TOTAL_SALIDA`;

DELIMITER $$
USE `hotel`$$
CREATE FUNCTION `F_TOTAL_SALIDA` (
FECHA_ING DATE, 
FECHA_SAL DATE, 
PRECIO FLOAT)
RETURNS FLOAT
DETERMINISTIC
BEGIN
	DECLARE PRECIO_TOTAL FLOAT;
    SET PRECIO_TOTAL = DATEDIFF(FECHA_SAL, FECHA_ING) * PRECIO; -- DE IZQUIERDA A DERECHA CUENTA POSITIVAMENTE O SUMA COMO SEA
	RETURN PRECIO_TOTAL;
END$$

DELIMITER ;

-- PROCEDIMIENTO ALM
USE `hotel`;
DROP procedure IF EXISTS `ACTUALIZAR_RESERVACION`;

DELIMITER $$
USE `hotel`$$
CREATE PROCEDURE `ACTUALIZAR_RESERVACION` (
IN P_ID_RESERVACION INT,
IN P_FECHA_ING DATE,
IN P_FECHA_SAL DATE,
IN P_PRECIO FLOAT,
OUT P_TOTAL FLOAT)
BEGIN
	SET p_total = F_TOTAL_SALIDA(p_fecha_ing, p_fecha_sal, p_precio);
	UPDATE RESERVACION
    SET TOTAL = p_total
    WHERE ID_RESERVACION = p_id_reservacion;
END$$

DELIMITER ;

-- TRIGGER
DELIMITER $$
CREATE TRIGGER ACTUALIZAR_ESTADO_HABITACION
AFTER INSERT ON RESERVACION
FOR EACH ROW
BEGIN
	UPDATE HABITACION
    SET ID_ESTADO = 0
    WHERE ID_HABITACION = NEW.ID_HABITACION;
END$$