-- PROCEDIMIENTO 2

SET @TOTAL_FINAL = 0;
CALL ACTUALIZAR_RESERVACION(1, '2025-06-20', '2025-06-22', 90, @TOTAL_FINAL);
SELECT @TOTAL_FINAL;
SELECT TOTAL FROM RESERVACION WHERE ID_RESERVACION = 1;
SELECT ID_ESTADO FROM HABITACION WHERE ID_HABITACION = 2; -- da 1 que es disponible